import { Checkout } from 'checkout-sdk-node';

let cko = new Checkout('your_client_secret_here', {
	client: 'ack_XXXXXXXXXXXX',
	scope: ['gateway'], // array of scopes
	environment: 'sandbox', // or "production"
});

// Or if you use api keys:
// const cko = new Checkout('sk_sbox_XXX', { pk: 'pk_sbox_XXX'}});

try {
	const payment = await cko.payments.request({
		source: {
			// inferred type: "token"
			token: 'tok_bzi43qc6jeee5mmnfo4gnsnera', // Generated by Checkout.Frames
			billing_address: {
				address_line1: 'Wall Street',
				address_line2: 'Dollar Avenue',
				city: 'London',
				state: 'London',
				zip: 'W1W W1W',
				country: 'GB',
			},
			phone: {
				country_code: '44',
				number: '7123456789',
			},
		},
		currency: 'USD',
		amount: 1000,
		payment_type: 'Regular',
		reference: 'ORDER 1234',
		description: 'Mint Tea',
		customer: {
			email: 'new_user@email.com',
			name: 'John Smith',
		},
		metadata: {
			value: 'My value',
		},
	});
} catch (err) {
	console.log(err.name);
}
