allOf:
  - $ref: '#/components/schemas/ChannelData'
  - type: object
    required:
      - sdk_app_id
      - sdk_max_timeout
      - sdk_ephem_pub_key
      - sdk_encrypted_data
      - sdk_reference_number
      - sdk_transaction_id
      - sdk_interface_type
      - sdk_ui_elements
    properties:
      channel:
        type: string
        enum:
          - app
      sdk_app_id:
        description: >
          Universally unique ID created upon all installations and updates of the 3DS Requestor App on a consumer device. This will be newly generated and stored by the 3DS SDK for each installation or update.
        type: string
        minLength: 36
        maxLength: 36
        example: dbd64fcb-c19a-4728-8849-e3d50bfdde39
      sdk_max_timeout:
        description: >
          Indicates maximum amount of time (in minutes) for all exchanges
        type: integer
        minimum: 5
        example: 5
      sdk_ephem_pub_key:
        $ref: '#/components/schemas/SdkEphemeralPublicKey'
      sdk_reference_number:
        description: >
          Identifies the vendor and version for the 3DS SDK that is integrated in a 3DS Requestor App, assigned by EMVCo when the 3DS SDK is approved.
        type: string
        maxLength: 32
        example: '3DS_LOA_SDK_PPFU_020100_00007'
      sdk_encrypted_data:
        description: >
          A JSON web encryption (JWE) object in compact serialization, containing data encrypted by the SDK for the Directory Server to decrypt.
        type: string
        maxLength: 64000
        example: '<device-information>'
      sdk_transaction_id:
        description: >
          Universally unique transaction identifier assigned by the 3DS SDK to identify a single transaction
        type: string
        minLength: 36
        maxLength: 36
        example: 'b2385523-a66c-4907-ac3c-91848e8c0067'
      sdk_interface_type:
        description: >
          Lists all of the SDK interface types that the device supports for displaying specific challenge user interfaces within the SDK
        type: string
        enum:
          - native
          - html
          - both
      sdk_ui_elements:
        description: >
          Lists all the user interface elements that the cardholder's device supports for displaying specific challenge user interfaces within the SDK
        type: array
        items:
          type: string
          enum:
            - text
            - single_select
            - multi_select
            - oob
            - html_other
