type: object
description: Use the processing object to influence or override the data sent during card processing
properties:
  order_id:
    type: string
    description: The number provided by the cardholder. Purchase order or invoice number may be used.
    maxLength: 17
    example: '123456789'
  otp_value:
    type: string
    description: One time password sent to customer by SMS.
    maxLength: 50
    example: '966557877988'
  tax_amount:
    type: number
    description: Contains the customer’s value-added tax registration number.
    minimum: 0
    example: 3000
  discount_amount:
    type: number
    description: The discount amount applied to the transaction by the merchant.
    minimum: 0
    example: 000
  duty_amount:
    type: number
    description: The total charges for any import/export duty included in the transaction.
    minimum: 0
    example: 000
  shipping_amount:
    type: number
    description: The total freight or shipping and handling charges for the transaction.
    minimum: 0
    example: 300
  shipping_tax_amount:
    type: number
    description: The tax amount of the freight or shipping and handling charges for the transaction.
    minimum: 0
    example: 100
  shipping_delay:
    type: integer
    description: 'The delay before the order will be shipped.'
  shipping_info:
    x-klarna-docs: https://developers.klarna.com/api/#order-management-api__create-capture__shipping_info
    x-cko-passthrough: true
    type: array
    description: The shipping information for the payment capture. Maximum 500 items.
    items:
      $ref: '#/components/schemas/ShippingInfo'
  purchase_country:
    type: string
    description: The country where the goods are purchased or the seller is based. ISO 3166 alpha-2 purchase country code.
    example: GB