post:
  tags:
    - Sources
  summary: Add a payment source
  description: |
    Add a reusable payment sources that can be later used to make one or more payments.
    Payment sources are linked to a specific customer and cannot be shared between customers.

  requestBody:
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/SourceRequest'
  responses:
    '201':
      description: Payment source added successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AddSourceResponse'
    '202':
      description: Payment source asynchronous or further action required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SourceRedirectResponse'
    '401':
      description: Unauthorized
    '422':
      description: Invalid data was sent
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    '502':
      description: Bad gateway