name: ReleasePRPost

on:
  pull_request:
    branches: [master]

env:
  CI: true

jobs:
  confluence_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      -   name: Post the release PR to Slack
          id: slack
          uses: slackapi/slack-github-action@v1.16.0
          with:
            channel-id: 'C03MDGXV0KT'
            payload: |
              {
                "type": "mrkdwn",
                "text": "New release PR for the API reference: ${{ github.event.pull_request.html_url}}"
              }
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
